# Python basic Programming Assignment 8

1.	Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
mat1 = np.array([[1,2],
        [3,4]])
mat2 = np.array([[5,6],
        [7,8]])

matsum = np.add(mat1,mat2)
print(matsum)

[[ 6  8]
 [10 12]]


2.	Write a Python Program to Multiply Two Matrices?

In [3]:
mat1 = np.array([[1,2],
        [3,4]])
mat2 = np.array([[5,6],
        [7,8]])

mulsum = np.dot(mat1,mat2)
print(mulsum)

[[19 22]
 [43 50]]


3.	Write a Python Program to Transpose a Matrix?

In [5]:
mat1 = np.array([
    [5,6,7],
    [7,8,9],
    [1,2,3]
])

transmat = np.transpose(mat1)
print(transmat)

[[5 7 1]
 [6 8 2]
 [7 9 3]]


4.	Write a Python Program to Sort Words in Alphabetic Order?

In [10]:
Arr = input("Enter string")
words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter stringDo you love python
Do
love
python
you


5.	Write a Python Program to Remove Punctuation From a String?

In [14]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

Arr = input("Enter a string with punctuations: ")


rem_punc = ""
for i in Arr:
    if i not in punctuations:
        rem_punc = rem_punc + i
 
print(rem_punc)

Enter a string with punctuations: "Hello, World! This is a test sentence."
Hello World This is a test sentence
